### ISSUE TITLE
gulp-tslint 7.1.0 is currently not supported

### ISSUE THREAD

**Issue by ketamin** [nicolas-schmitt/gulp-tslint-jenkins-reporter#14]
In our environment is gulp-tslint 7.1.0 installed.

> gulp-tslint-jenkins-reporter@1.0.6 requires a peer of gulp-tslint@^5.0.0 || ^6.1.3 || 7.0.1 but none was installed.

I get this warning twice per update and it seems, it could be fixed with adding the ^ for version 7.x.y
`"peerDependencies": {
    "gulp-tslint": "^5.0.0 || ^6.1.3 || ^7.0.1"
  },`

**Comment by nicolas-schmitt** [comment]
Hi, you're absolutely right.
A 1.0.7 is out fixing that problem.

Thanks for the feedback !
