### ISSUE TITLE
Support for TSLint Rule Severity

### ISSUE THREAD

**Issue by mattdsteele** [nicolas-schmitt/gulp-tslint-jenkins-reporter#15]
tslint 5.0 introduced the notion of rule severity, allowing rules to either have an error or a warning severity.

The reporter should be able to populate the `severity` field based on this, I think.

This *might* be dependent on getting severity from gulp-tslint: https://github.com/panuhorsmalahti/gulp-tslint/issues/116

**Comment by nicolas-schmitt** [comment]
Hey, thanks for the feedback :smile_cat: 
I'll check this out asap

**Comment by nicolas-schmitt** [comment]
Hi again, i just published a 1.1.0 which handles the severity field :)
Let me know if anything else needs to be fixed
