### ISSUE TITLE
Update dependency

### ISSUE THREAD

**Issue by ElsayedTaha** [nicolas-schmitt/gulp-tslint-jenkins-reporter#20]
Hello,

Can you please update plexer to latest version? This is needed in order to fix advisory 534 (plexer uses debug package, which in latest version they fixed this issue, but plexer version in your package is not latest)

Thanks!

**Comment by nicolas-schmitt** [comment]
Hi,

Thanks for the heads up! However i looked at the current version of plexer and it still uses debug:
https://www.npmjs.com/package/plexer

Where did you see that this issue was fixed ? I may be missing something but i don't see how switching from 1.0.1 to 1.0.2 will help (not that i mind)

**Comment by nicolas-schmitt** [comment]
Ok never mind, i dropped plexer entirely (as well as most of lodash for that matter). `npm audit` doesn't report any vulnerabilities anymore 😸 

Let me know if the latest version (`1.2.0`) suits you!

**Comment by ElsayedTaha** [comment]
> Ok never mind, i dropped plexer entirely (as well as most of lodash for that matter). `npm audit` doesn't report any vulnerabilities anymore 
> 
> Let me know if the latest version (`1.2.0`) suits you!

Thank you, indeed this fixed the issue!
