### ISSUE TITLE
plugin not compatible with gulp-tslint@^6.0 (only gulp-tslint@^5.0)

### ISSUE THREAD

**Issue by jesperronn** [nicolas-schmitt/gulp-tslint-jenkins-reporter#8]
Installing this plugin is impossible when you refer to most recent `gulp-tslint`in `package.json`.

```
├── UNMET PEER DEPENDENCY gulp-tslint@6.1.1
└─┬ gulp-tslint-jenkins-reporter@1.0.3 
  ├── lodash@4.15.0 
  ├─┬ mkdirp@0.5.1 
  │ └── minimist@0.0.8 
  ├── plexer@1.0.1 
  ├─┬ upath@0.1.7 
  │ └── underscore.string@2.3.3 
  └── vinyl@1.2.0 

npm WARN gulp-tslint-jenkins-reporter@1.0.3 requires a peer of gulp-tslint@^5.0.0 but none was installed.
```

Would it be possible to release a new version compatible with `gulp-tslint@^6.0`? 

Thanks!

**Comment by serajam** [comment]
Same here

**Comment by nicolas-schmitt** [comment]
Hi,
since the reporter works on both gulp-tslint@5.x and gulp-tslint@6.x, I made the version requirement a bit more permissive. This should remove the warning.
